### PR TITLE
Fix template texts localizing/escaping

### LINKED ISSUE #632: Localize option tries to localize already localized strings breaking the patters.
## What
The localize option tries to localize already localized strings, breaking the patterns.

Example output of saving TT4 theme using 'Localize Text' option enabled:
```
<!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left"><?php echo __('Experience the fusion of imagination and expertise with Études <?php echo __('Architectural Solutions', 'twentytwentyfour');?>.', 'twentytwentyfour');?></p>
<!-- /wp:paragraph --></div>
``` 
Please observe that an echo statement is inside another echo statement, which will result in a parse error. This breaks the pattern where this is included.

## Expected
The localize functionality should not try to localize already localized text.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Fix template texts localizing/escaping.

Fixes: https://github.com/WordPress/create-block-theme/issues/632

## Why?
The current implementation consisting of:
1. Collect all the strings from the templates markup using regex.
2. Search and replace the strings collected.

This approach is flawed because it fails, for example, when there are substrings. The problem is explained in this comment: https://github.com/WordPress/create-block-theme/issues/632#issuecomment-2112602045

☣️ The severity of the problem is high because the resulting templates/patterns are broken because the plugin is producing invalid markup.

## How?
This PR improves the approach around escaping block strings for translation. It avoids the substring problem by just considering the HTML content block by block.
The new implementation consist of:
1. Parse the template markup with the core's function `parse_blocks().`
2. In the blocks that can contain text, use regex to update the HTML content of the block 'innetContent' property with the escaped text.
3.  Serialize the template blocks to markup again using core's `serialize_blocks()` function.

### CODE REVIEW

File: admin/create-theme/theme-locale.php [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+
+		$string = addcslashes( $string, "'" );
+		return "<?php echo __('" . $string . "', '" . wp_get_theme()->get( 'TextDomain' ) . "');?>";
+	}
+
+	/**
+	 * Get a replacement pattern for escaping the text from the html content of a block.
+	 *
+	 * @param string $block_name The block name.
+	 * @return string|array|null The regex pattern to match the content that needs to be escaped.
```
Comment (pbking) [inline admin/create-theme/theme-locale.php]: Looks like it always returns an array (which is my 'druthers), so just `array|null` right?

**Comment by pbking** [comment]
I had one teeny tiny inconsequential nit.

This is great to bring in and fixes the problem at hand and enhances the tests quite a bit.

**Review by pbking — APPROVED** [review]

File: admin/create-theme/theme-locale.php (hunk 1 above)
Comment (pbking) [reply admin/create-theme/theme-locale.php]: updated
