### PR TITLE
Remove white spaces from theme slugs

### LINKED ISSUE #242: Export: Getting `Template part has been deleted or is unavailable: header` after uploading to a new site
While working on a theme created from scratch with **Create Block Theme** I opted to export the theme using the _Export the activated theme with user changes_ option:

image

I got a zip bundle and uploaded to another site. On that new site I visited the editor and was shown a message `Template part has been deleted or is unavailable: header` (footer as well).

image

#### Workaround
I noticed then that the `templates/index.html` file part of the bundle created by the export was referring to the header part like this:

```
<!-- wp:template-part {"slug":"header","tagName":"header","theme":"new blank theme"} /-->
```
... while my original file (the one generated from scratch) read:
```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->
```

After removing `"theme":"new blank theme"` the template worked properly loading the index part. 

### How to reproduce

1. On a fresh site, install Create Block Theme
1. Visit Appearance -> Create Block Theme
1. **Create a blank theme**. Name it **Le Theme**.
1. Activate the Theme in Appearance -> Themes
1. **Export the theme:** Visit Appearance -> Create Block Theme and export the theme. Keep the downloaded bundle somewhere.
1. **Deactivate and delete the recently created** theme  **Le Theme**: Visit Appearance -> Create Block Theme, switch to **Twenty Twenty-Three**, then delete **Le Theme**.
1. Upload and activate the downloaded zip from step 5.
2. Visit the Editor.
3. Confirm the part is missing. Expect to see `Template part has been deleted or is unavailable: header` and `Template part has been deleted or is unavailable: footer` messages.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
- Remove white spaces from the theme slug
- Removing the removal of the key in the template parts links in templates because this is not necessary.

## How to test?
Follow the steps detailed in the description of: #242

Fixes: https://github.com/WordPress/create-block-theme/issues/242

### CODE REVIEW

File: admin/class-create-block-theme-admin.php [hunk 1]
```diff
@@ -469,6 +469,7 @@ function get_theme_slug( $new_theme_name ) {
 
 		$old_slug = wp_get_theme()->get( 'TextDomain' );
  		$new_slug = sanitize_title( $new_theme_name );
+		$new_slug = preg_replace('/\s+/', '', $new_slug); // Remove spaces
```
Comment (madhusudhand) [inline admin/class-create-block-theme-admin.php:472]: Not sure if I am missing a usecase, isn't it taken care by `sanitize_title`?

File: admin/class-create-block-theme-admin.php [hunk 2]
```diff
@@ -729,9 +720,6 @@ function make_media_blocks_local ( $nested_blocks ) {
 				case 'core/media-text':
 					$block = $this->make_mediatext_block_local( $block );
 					break;
-				case 'core/template-part':
-					$block = $this->add_theme_attr_to_template_part_block( $block );
-					break;
```
Comment (madhusudhand) [inline admin/class-create-block-theme-admin.php:734]: A theme attribute is still attached to template parts.
```
<!-- wp:template-part {"slug":"header","tagName":"header","theme":"themes/blockbase2"} /-->
```

**Review by oskosk — APPROVED** [review]
This worked well for me following the steps of #242!

File: admin/class-create-block-theme-admin.php (hunk 1 above)
Comment (matiasbenedetto) [reply admin/class-create-block-theme-admin.php:472]: `sanitize_title` doesn't remove the white spaces, we need to remove them to create a slug.

File: admin/class-create-block-theme-admin.php (hunk 2 above)
Comment (matiasbenedetto) [reply admin/class-create-block-theme-admin.php:734]: What's the problem with that? The template parts are loaded fine, I don't know why they shouldn't have the theme key.

**Comment by oskosk** [comment]
~When testing this PR it worked for me. I copied the file's content and pasted it on a site running Create Block Theme 1.6.0...~

~But after 1.6.1 was released, I faced this bug again on a fresh site with **Create Block Theme 1.6.1**. The same steps as described in #242, but the template is now indeed exported referencing the part with spaces stripped on the `theme` attribute.~

~In this capture, I show the new site where I uploaded the recently generated theme from another site (with Create Block Theme 1.6.1).~

~You can see that the theme attribute is there without spaces, but the part does not render.~

### Edit: See https://github.com/WordPress/create-block-theme/pull/244#issuecomment-1448634501

https://user-images.githubusercontent.com/746152/221923062-00fe3355-80b8-4884-94d9-9cb7d8fbd12f.mov

**Comment by oskosk** [comment]
>When testing this PR it worked for me. I copied the file's content and pasted it on a site running Create Block Theme 1.6.0...

~I'm sorry, but I think I didn't test properly at the time. I just retested doing this ⬆️  and the problem persisted in 1.6.0 with the changes from the PR applied~

Edit: See https://github.com/WordPress/create-block-theme/pull/244#issuecomment-1448634501

**Comment by oskosk** [comment]
Ok, I found out what happened. I was uploading a file named `letheme (2).zip` (a result of downloading multiple times) that ended up creating a folder named `letheme-2` in the site, so the editor requests to `wp-json/wp/v2/template-parts/letheme//header?context=edit&_locale=user` were failing. Sorry for the noise
