### PR TITLE
Check ZipArchive class before zip export

### LINKED ISSUE #492: Fatal error: Uncaught Error: Call to undefined method WP_Error::addThemeDir()
ERROR on Creating a Child Theme, OR, Cloning a Theme.  Help !
Wordpress Version 6.4.2
Installed Theme - Twenty Twenty-Four  Version: 1.0

Fatal error: Uncaught Error: Call to undefined method WP_Error::addThemeDir() in D:\ThemeBuilder\wp-content\plugins\create-block-theme\admin\create-theme\theme-zip.php:103 Stack trace: #0 D:\ThemeBuilder\wp-content\plugins\create-block-theme\admin\class-create-theme.php(266): Theme_Zip::add_templates_to_zip(Object(WP_Error), 'user', 'sample2024new...') #1 D:\ThemeBuilder\wp-content\plugins\create-block-theme\admin\class-create-theme.php(470): Create_Block_Theme_Admin->create_child_theme(Array, Array) #2 D:\ThemeBuilder\wp-includes\class-wp-hook.php(324): Create_Block_Theme_Admin->blockbase_save_theme('') #3 D:\ThemeBuilder\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #4 D:\ThemeBuilder\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #5 D:\ThemeBuilder\wp-admin\admin.php(175): do_action('admin_init') #6 D:\ThemeBuilder\wp-admin\themes.php(10): require_once('D:\\Programs\\Xam...') #7 {main} thrown in D:\ThemeBuilder\wp-content\plugins\create-block-theme\admin\create-theme\theme-zip.php on line 103

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #492

This PR displays an appropriate error message when a process that creates a zip file requires the ZipArchive class and the class does not exist.

Suggestions for displayed text are also welcome!

image

image

## Testing Instructions

To test this PR, you need to disable the zip extension locally. For wp-env, please follow the steps below.

- Run wp-env: `npm run wp-env start`
- Check the container name: `docker ps`
- Go inside the container: `docker exec -it {YOUR-CONTAINER-NAME}-wordpress-1 bash`
- Remove zip extension: `rm /usr/local/etc/php/conf.d/docker-php-ext-zip.ini`
- Restart Apache: `/etc/init.d/apache2 reload`
- Exit the container: `exit`
- Check the Site Health page to make sure the zip extension is disabled:

After that, confirm that an error message is displayed when you perform the following operations:

- Site Editor
  - Create Block Theme Option > Export Zip
- Appearance > Create Block Theme
  - Export {themeName}
  - Create sibling of {themeName}
  - Create child of {themeName}
  - Clone {themeName}

P.S. Restart wp-env and the zip extension will be automatically enabled again.

## Supplement 

In addition to the REST API endpoint that this PR changes, the ZipArchive class is also used in the callback functions of the following two endpoints. However, these two endpoints currently don't seem to be called from anywhere.

| Endpoint                                  | Callback function              |
| ----------------------------------------- | ------------------------------ |
| create-block-theme/v1/export-clone/       | rest_export_cloned_theme       |
| create-block-theme/v1/export-child-clone/ | rest_export_child_cloned_theme |

### CODE REVIEW

File: admin/class-create-theme.php [hunk 1]
```diff
@@ -462,6 +462,9 @@ function blockbase_save_theme() {
 				$this->create_blank_theme( $_POST['theme'], $_FILES['screenshot'] );
 
 				add_action( 'admin_notices', array( 'Form_Messages', 'admin_notice_blank_success' ) );
+			} elseif ( ! class_exists( 'ZipArchive' ) ) {
+				// Avoid running if ZipArchive is not enabled.
+				add_action( 'admin_notices', array( 'Form_Messages', 'admin_notice_error_unsupported_zip_archive' ) );
```
Comment (t-hamano) [inline admin/class-create-theme.php:467]: Everything after this should require the zipArchive class.

**Review by pbking — APPROVED** [review]
Thank you for the steps to disable zip in my wp-env.

Tests well, works as expected.  I think the copy used is fine.

🚢
